version: 2

project_name: mutiny

before:
  hooks:
    - go mod tidy

builds:
  - id: mutiny
    binary: mutiny
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: linux
    builds: [mutiny]
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE*
      - README*
      - build/mutiny.desktop
      - build/mutiny-tui.desktop
      - build/mutiny.service
      - build/icons/*
  - id: windows
    builds: [mutiny]
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}"
    format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256sums.txt"
  algorithm: sha256

release:
  github:
    owner: Lumb3rH4ck
    name: mutiny
  draft: false
  prerelease: auto
